//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P00196754_Md_Nawaz_Sharif_Nahid_ExpenseTracker
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCustomer
    {
        public int cId { get; set; }
        public string Name { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public Nullable<int> uId { get; set; }
    
        public virtual tblUser tblUser { get; set; }
    }
}
