//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P00196754_Md_Nawaz_Sharif_Nahid_ExpenseTracker
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblExpenseItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblExpenseItem()
        {
            this.tblExpenseRecords = new HashSet<tblExpenseRecord>();
        }
    
        public int eiId { get; set; }
        public string ItemName { get; set; }
        public decimal Cost { get; set; }
        public string Description { get; set; }
        public int ExpenseCategoryId { get; set; }
        public int UserId { get; set; }
    
        public virtual tblExpenseCategory tblExpenseCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblExpenseRecord> tblExpenseRecords { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
